# AdaIR
network=AdaIR 
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/AdaIR/AdaIR-net-current.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/AdaIR_v2/AdaIR_v2-net-best_val.pth"
tester_save_name=AdaIR

# Restormer 
network=Restormer
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer/Restormer-net-best_train.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/Restormer_v2/Restormer_v2-net-best_val.pth"
tester_save_name=Restormer

# Restormer_Pre 
network=Restormer
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_Pre/Restormer_Pre-net-best_val.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/Restormer_Pre_v2/Restormer_Pre_v2-net-best_val.pth"
tester_save_name=Restormer_Pre 

# Restormer_GGB
network=Restormer_GGB 
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_GGB/Restormer_GGB-net-best_val.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/Restormer_GGB_v2/Restormer_GGB_v2-net-best_val.pth"
tester_save_name=Restormer_GGB

# Restormer_GGB2
network=Restormer_GGB2
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_GGB2/Restormer_GGB2-net-best_val.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/Restormer_GGB2_v2/Restormer_GGB2_v2-net-best_val.pth"
tester_save_name=Restormer_GGB2


# Restormer_GGB_Pre
network=Restormer_GGB 
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_GGB_Pre/Restormer_GGB_Pre-net-best_val.pth"
net_checkpath2=""
tester_save_name=Restormer_GGB_Pre

# Restormer_GGB3
network=Restormer_GGB3
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_GGB3/Restormer_GGB3-net-best_val.pth"
net_checkpath2="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/deeplession/ckpt/Restormer_GGB3/Restormer_GGB3-net-best_val.pth"

# Restormer_GGB3_Pre_CL 
network=Restormer_GGB3_CL
net_checkpath1="/mnt/nas/wsy/Codes/NewCodes/demo3/Experiments/aapm/ckpt/Restormer_GGB3_Pre_CL/Restormer_GGB3_Pre_CL-net-best_val.pth"
net_checkpath2=""
